services:
  - type: web
    name: customer-segmentation
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: python app.py
    envVars:
      - key: MONGO_DB_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: ap-south-1
